//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.flows

import com.voxeldev.tgdrive.files.api.channels.Supergroup
import com.voxeldev.tgdrive.mappers.channels.SupergroupMapper
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.tdlib.TdApi
import org.drinkless.tdlib.TdApi.UpdateSupergroupFullInfo

/**
 * emits [Supergroup] if some data of a supergroup or a channel has changed. This update is
 * guaranteed to come before the supergroup identifier is returned to the application.
 */
fun TelegramFlow.supergroupFlow(supergroupMapper: SupergroupMapper): Flow<Supergroup> =
    this.getUpdatesFlowOfType<TdApi.UpdateSupergroup>()
        .mapNotNull { supergroupMapper.toResponse(supergroup = it.supergroup) }

/**
 * emits [UpdateSupergroupFullInfo] if some data in supergroupFullInfo has been changed.
 */
fun TelegramFlow.supergroupFullInfoFlow(): Flow<UpdateSupergroupFullInfo> =
    this.getUpdatesFlowOfType()
